my second commit
Clementify/Lesson_1_and_2_Task_2_Obi_Clementina pull request #1
Opened 2023-05-03 13:57 UTC by Clementify

I am done with my Lesson 1 and 2 task2 please come and review @ChidiPatrick and @Promise-J

2023-05-04 11:06 UTC, ChidiPatrick requested changes
Please work on your indentation, and place your contents in proper elements

2023-05-04 11:06 UTC, ChidiPatrick commented on html/index.html
> +            <img src="/tailoring material.jpg" alt="tailoring material" class="img">
Close your  image tag

2023-05-04 11:06 UTC, ChidiPatrick commented on html/index.html
> +
Please indent your code proper. The space is too much

2023-05-04 11:06 UTC, ChidiPatrick commented on html/index.html
> +
space is too much

2023-05-05 15:12 UTC, ChidiPatrick requested changes
Work on your indentation

2023-05-05 15:12 UTC, ChidiPatrick commented on html/index.html
> +                    <h2>ALL YOU NEED TO KNOW ABOUT TAILORING MATERIAL BUSINESS</h2>
Work on your indentation

2023-05-05 15:35 UTC, Clementify commented on html/index.html
> +                    <h2>ALL YOU NEED TO KNOW ABOUT TAILORING MATERIAL BUSINESS</h2>
Alright sir.

2023-05-05 16:11 UTC, ChidiPatrick approved these changes
nice work

2023-05-05 16:15 UTC, merged